version: '3'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    environment:
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN} # Replace with your actual token
      - CI_SERVER_URL=${GITLAB_URL} # Replace with your GitLab instance URL if self-hosted
      - RUNNER_NAME=${RUNNER_NAME}
      - REGISTER_NON_INTERACTIVE=true
      - DOCKER_TLS_CERTDIR="" # Disable TLS for Docker communication
    volumes:
      - './config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock' # Enable communication with Docker host
    entrypoint: |
      bash -c '
        if [[ ! -f /etc/gitlab-runner/config.toml ]]; then
          gitlab-runner register --non-interactive \
            --url "$CI_SERVER_URL" \
            --registration-token "$REGISTRATION_TOKEN" \
            --executor "docker" \
            --docker-image "docker:latest" \
            --description "$RUNNER_NAME" \
            --tag-list "docker" \
            --run-untagged="true" \
            --locked="false" \
            --access-level="not_protected";
        fi
        gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner
      '

  docker-dind:
    image: docker:24-dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR="" # Disable TLS for Docker-in-Docker
    volumes:
      - '/var/lib/docker'


